### PR TITLE
Manually enhanced grammar with specs.

### PR DESCRIPTION
**Pull request by hillaby**
All the examples from ChucK source code look good. I basically did it for my own use, but it can be useful for anyone.

### CODE REVIEW

**Comment by cjwilburn** [comment]
LGTM. Thanks for putting all of this in. Much appreciated!

**Review by cjwilburn — CHANGES_REQUESTED** [review]
I'd say this is good to go along with a semantic version bump.

**Comment by hillaby** [comment]
I have changed README, CHANGELOG and major version on the branch.

**Review by cjwilburn — APPROVED** [review]

**Review by cjwilburn — APPROVED** [review]
LGTM

**Comment by cjwilburn** [comment]
These are great improvements. Thanks so much @hillaby! I'll merge it in within the next 24 hours or so.

**Comment by hillaby** [comment]
Thanks for merging the changes. Will you create a new release and upload it to https://atom.io/packages/language-chuck ? I don't think I have the rights to do so. Thanks!

**Pull request merged**
